### ISSUE TITLE
for in 구문과 for of 구문의 차이점을 설명

### ISSUE THREAD

**Issue by LeeJehwan** [Alpha-ka-JS/Modern-JS#37]
https://github.com/Alpha-ka-JS/Modern-JS/blob/ec12ce01ac92f2c92831ed995a8effbbe4e86031/JeongSungWon/ch8/ch8_11.js#L93-L96

아래 댓글로 정리해주시고 다음 리뷰때 설명해주시면 감사하겠습니다.

**Comment by sungwon2054** [comment]
for ~ in => 객체의 속성 순환 
for ~ of => 배열 순환 (객체의 Data) 

하지만 내용이 부족하다 생각하여 더 찾아본 결과
prototype chain에 의하여 달라진다고 하는데 아직 prototype에 대한 공부를 하지 않아 확인하고 정리하여 다시 올리겠습니다.

**Comment by sungwon2054** [comment]
해결하고 close 하겠습니다.

**Comment by junekinns** [comment]
LGTM
